name: CI/CD

on:
  push:
    branches: [ main ]
    tags: 
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.202
    - name: Install dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish --configuration Release --no-restore --version-suffix $GITHUB_RUN_NUMBER --output build
    - name: Test
      working-directory: ./VnetCapacityPlanner.Tests
      run: | 
        dotnet tool install --global Microsoft.Playwright.CLI
        dotnet restore
        dotnet build
        playwright install
        dotnet test

  release:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.202
    - name: Install dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish --configuration Release --no-restore --version-suffix $GITHUB_RUN_NUMBER --output build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.0.0-beta-01
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/wwwroot
        SINGLE_COMMIT: true 

