name: CI/CD

on:
  push:
    branches: [ master ]
    tags: 
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --version-suffix $GITHUB_RUN_NUMBER

  release:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish --configuration Release --no-restore --version-suffix $GITHUB_RUN_NUMBER --output build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.0.0-beta-01
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/wwwroot
        SINGLE_COMMIT: true 

