name: Release to gh-pages

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish --configuration Release --no-restore --output build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.0.0-beta-01
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/wwwroot
        SINGLE_COMMIT: true 

